[package]
name = "ascii_arcade"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.29.0", default-features = false, features = ["termion"] }
readonly = "0.2.12"
termion = "4.0.3"
uuid = { version = "1.15.1", features = ["v4"] }
