name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: RUST_BACKTRACE=full cargo test --all
    - name: Formatting checks
      run: cargo fmt --all --check
    - name: Linting checks
      run: cargo clippy --all-targets --all-features --workspace -- -D warnings
    - name: Documentation checks
      run: cargo doc --no-deps --document-private-items --all-features --workspace --examples

# REFERENCES:
# > https://github.com/rust-github/template/blob/main/template/.github/workflows/ci.yml
